---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: compute-worker-keda
  namespace: infosys-benchmark
spec:
  scaleTargetRef:
    name: compute-worker
  minReplicaCount: 1
  maxReplicaCount: 20
  pollingInterval: 15
  cooldownPeriod: 60
  triggers:
  - type: prometheus
    metricType: AverageValue
    metadata:
      serverAddress: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
      metricName: cpu_cores_total
      threshold: '0.035'
      query: |
        sum(rate(container_cpu_usage_seconds_total{
          namespace="infosys-benchmark",
          container="compute"
        }[1m]))
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 60
        scaleUp:
          stabilizationWindowSeconds: 0
